targets:
  $default:
    sources:
      - lib/**
      - lib/core/gq_queries/**
      - gq_scheme.graphql
      - $package$
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: gq_scheme.graphql
              queries_glob: lib/core/gq_queries/*.graphql
              output: lib/core/gq_models/gq_models.dart
              naming_scheme: simple
          scalar_mapping:
            - graphql_type: Long
              dart_type: int